ignored_config_entities:
  - acquia_connector.settings
  - acquia_search.settings
  - 'google_tag.container.*'
  - 'system.site:name'
  - 'system.site:mail'
  - 'system.site:slogan'
  - 'system.site:page.front'
  - 'system.site:page.403'
  - 'system.site:page.404'
  - core.menu_static_link_overrides
  - 'block.block.*'
  - media_acquiadam.settings
  - 'xmlsitemap.xmlsitemap.*'
  - xmlsitemap_engines.settings
  - robotstxt.settings
  - 'new_relic_rpm.settings:api_key'
